// apps/web/src/components/keyboard-shortcuts-modal.tsx
"use client"

import { KEYBOARD_SHORTCUTS } from "@/hooks/use-hotkeys"

interface KeyboardShortcutsModalProps {
  open: boolean
  onClose: () => void
}

export function KeyboardShortcutsModal({ open, onClose }: KeyboardShortcutsModalProps) {
  if (!open) return null

  const categories = [...new Set(KEYBOARD_SHORTCUTS.map(s => s.category))]

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center px-4"
      role="dialog"
      aria-modal="true"
      aria-labelledby="shortcuts-title"
    >
      <div className="absolute inset-0 bg-background/60 backdrop-blur-sm" onClick={onClose} />
      <div className="relative bg-background border border-border rounded-xl shadow-2xl p-6 w-full max-w-md">
        <h2 id="shortcuts-title" className="text-lg font-semibold mb-4">Keyboard Shortcuts</h2>
        {categories.map(cat => (
          <div key={cat} className="mb-4">
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">{cat}</h3>
            <div className="space-y-1">
              {KEYBOARD_SHORTCUTS.filter(s => s.category === cat).map(s => (
                <div key={s.keys} className="flex items-center justify-between text-sm">
                  <span className="text-muted-foreground">{s.description}</span>
                  <kbd className="font-mono text-xs bg-muted border border-border rounded px-2 py-0.5">{s.keys}</kbd>
                </div>
              ))}
            </div>
          </div>
        ))}
        <button
          onClick={onClose}
          className="mt-4 w-full text-sm py-2 rounded-lg bg-muted hover:bg-muted/80 transition-colors"
          aria-label="Close keyboard shortcuts"
        >
          Close
        </button>
      </div>
    </div>
  )
}

// apps/web-solid/src/components/KeyboardShortcutsModal.tsx
import { Show } from 'solid-js'

interface Props {
  open: boolean
  onClose: () => void
}

const shortcuts = [
  { key: 'j / k', description: 'Navigate files down / up' },
  { key: 'c', description: 'Add inline comment on selected line' },
  { key: 'o', description: 'Toggle AI priority ordering' },
  { key: '⌘K', description: 'Open command palette' },
  { key: '?', description: 'Show keyboard shortcuts' },
  { key: 'g d', description: 'Go to dashboard' },
  { key: 'Esc', description: 'Close modal / cancel comment' },
]

export function KeyboardShortcutsModal(props: Props) {
  return (
    <Show when={props.open}>
      <div
        class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 backdrop-blur"
        onClick={props.onClose}
      >
        <div
          class="w-full max-w-sm bg-slate-900 border border-slate-700 rounded-xl shadow-2xl overflow-hidden"
          onClick={e => e.stopPropagation()}
        >
          <div class="flex items-center justify-between px-4 py-3 border-b border-slate-800">
            <h2 class="text-sm font-semibold text-white">Keyboard Shortcuts</h2>
            <button class="text-slate-600 hover:text-slate-400 text-xs" onClick={props.onClose}>
              ESC
            </button>
          </div>
          <div class="p-4 space-y-1">
            {shortcuts.map(({ key, description }) => (
              <div class="flex items-center justify-between py-2 border-b border-slate-800/50 last:border-0">
                <span class="text-slate-400 text-sm">{description}</span>
                <kbd class="bg-slate-800 border border-slate-700 text-slate-300 text-xs px-2 py-0.5 rounded font-mono">
                  {key}
                </kbd>
              </div>
            ))}
          </div>
        </div>
      </div>
    </Show>
  )
}
