// apps/web/src/components/cluster-panel.tsx
"use client"

interface Cluster {
  cluster_id: number
  label: string
  files: string[]
  coherence: number
}

interface ClusterPanelProps {
  clusters: Cluster[]
  selectedClusterId: number | null
  onSelectCluster: (id: number | null) => void
}

const CLUSTER_COLORS = [
  "bg-purple-500", "bg-blue-500", "bg-cyan-500", "bg-teal-500",
  "bg-indigo-500", "bg-violet-500", "bg-fuchsia-500", "bg-pink-500",
]

export function ClusterPanel({ clusters, selectedClusterId, onSelectCluster }: ClusterPanelProps) {
  if (clusters.length === 0) {
    return (
      <div className="p-3 text-xs text-muted-foreground text-center">
        Semantic groups unavailable
      </div>
    )
  }

  return (
    <div className="p-3 space-y-1">
      <div className="text-xs font-semibold text-muted-foreground mb-2 uppercase tracking-wide">
        Semantic Groups
      </div>
      
      <button
        className={`w-full text-left px-2 py-1.5 rounded text-xs transition-colors ${selectedClusterId === null ? "bg-muted font-medium" : "hover:bg-muted/50"}`}
        onClick={() => onSelectCluster(null)}
      >
        All files
      </button>
      
      {clusters.map((cluster, i) => {
        const isSelected = selectedClusterId === cluster.cluster_id
        const color = CLUSTER_COLORS[i % CLUSTER_COLORS.length]
        
        return (
          <button
            key={cluster.cluster_id}
            className={`w-full text-left px-2 py-1.5 rounded text-xs transition-colors flex items-start gap-2 ${isSelected ? "bg-muted font-medium" : "hover:bg-muted/50"}`}
            onClick={() => onSelectCluster(isSelected ? null : cluster.cluster_id)}
            aria-pressed={isSelected}
          >
            <span className={`mt-0.5 w-2 h-2 rounded-full shrink-0 ${color}`} />
            <span className="flex-1 min-w-0">
              <span className="block truncate">{cluster.label}</span>
              <span className="text-[10px] text-muted-foreground">
                {cluster.files.length} files · {(cluster.coherence * 100).toFixed(0)}% coherence
              </span>
            </span>
          </button>
        )
      })}
    </div>
  )
}

// apps/web-solid/src/components/pr-review/ClusterPanel.tsx
import { For, Show } from 'solid-js'
import type { Cluster } from '@/lib/ml'

interface Props {
  clusters: Cluster[]
  selectedCluster: string | null
  onSelectCluster: (id: string | null) => void
  isLoading: boolean
}

export function ClusterPanel(props: Props) {
  return (
    <div class="p-3 space-y-2">
      <div class="text-xs font-medium text-slate-400 uppercase tracking-wider px-1">
        Semantic Groups
      </div>
      <Show when={props.isLoading}>
        {[...Array(3)].map(() => (
          <div class="h-16 bg-slate-800 rounded-lg animate-pulse" />
        ))}
      </Show>
      <Show when={!props.isLoading && props.clusters.length === 0}>
        <p class="text-xs text-slate-600 px-1">
          All changes appear related — no distinct groups found.
        </p>
      </Show>
      <For each={props.clusters}>
        {cluster => {
          const isSelected = () => props.selectedCluster === cluster.id
          return (
            <button
              class={`w-full text-left rounded-lg p-3 border transition-colors
                ${isSelected()
                  ? 'border-opacity-100 bg-opacity-20'
                  : 'border-slate-700 hover:border-slate-600 bg-slate-800/30'}
              `}
              style={isSelected() ? {
                'border-color': cluster.color,
                'background-color': `${cluster.color}15`,
              } : {}}
              onClick={() => props.onSelectCluster(isSelected() ? null : cluster.id)}
            >
              <div class="flex items-center gap-2 mb-1">
                <div class="w-2 h-2 rounded-full" style={{ background: cluster.color }} />
                <span class="text-xs font-medium text-slate-200">{cluster.label}</span>
                <span class="ml-auto text-xs text-slate-500">{cluster.files.length} files</span>
              </div>
              <div class="text-xs text-slate-500">
                Coherence: {Math.round(cluster.coherence * 100)}%
              </div>
            </button>
          )
        }}
      </For>
    </div>
  )
}
